sudo: required
services:
  - docker

before_install:
  - docker build . -t daruom/complex -f ./client/dev.Dockerfile

script:
  - docker run -e CI=true daruom/complex npm test

after_success:
  - docker build -t daruom/complex-client ./client
  - docker build -t daruom/complex-nginx ./nginx
  - docker build -t daruom/complex-server ./server
  - docker build -t daruom/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push daruom/complex-client
  - docker push daruom/complex-nginx
  - docker push daruom/complex-server
  - docker push daruom/complex-worker
