sudo: required
services:
  - docker

before_install:
  - docker build ./client -t daruom/complex -f ./client/dev.Dockerfile

script:
  - docker run -e CI=true daruom/complex npm test

after_success:
  - docker build -t daruomm/complex-client ./client
  - docker build -t daruomm/complex-nginx ./nginx
  - docker build -t daruomm/complex-server ./server
  - docker build -t daruomm/complex-worker ./worker
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  - docker push daruomm/complex-client
  - docker push daruomm/complex-nginx
  - docker push daruomm/complex-server
  - docker push daruomm/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket-name: elasticbeanstalk-us-east-2-188676039639
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
